# Circle CI 2.0 Especification
version: 2
jobs:
  build:
    # Docker image selected.
    docker:
      - image: circleci/node:8-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    # Setup the ENV VARIABLES used in the  consequent steps. 
    environment:    
      # The Service Name must be the same you have in your package.json, Dockerfile &
      # docker-compose.yml.
      SERVICE_NAME: formiojs
      # Git User Email & Name
      GIT_USER_EMAIL: ci@kelsus.com
      GIT_USER_NAME: CircleCI
    branches:
      only:
        - kelsus/publish-v4.7.8
    steps:
      # Setup enviroment on Circle CI. This enable the support for docker-compose.
      # - setup_remote_docker
      # Enables a mode of the shell where all executed commands are printed to the terminal.
      - run: set -x
      # Checking out the project from the repository.
      - checkout
      - run:
          name: Allow access to private npm.
          command: printf "%s\n" "_auth=$ARTIFACTORY_TOKEN" "email=ci@kelsus.com" "always-auth=true" > .npmrc
      - run:
          name: For your npm command line client to work with Artifactory, you first need to set the default npm registry with an Artifactory npm repository
          command: npm config set registry https://kbsforce.jfrog.io/kbsforce/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm ci --verbose
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:  
          name: Configure git to commit and push the tag.
          command: git config --global user.email $GIT_USER_EMAIL && git config --global user.name $GIT_USER_NAME && git branch -u origin/$CIRCLE_BRANCH
      - deploy: 
          name: Build and publish npm package
          command: npm run publish
      - store_artifacts:
          path: test-results.xml
          prefix: tests